name: CI-CD Demo

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # Latest version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    needs: build-and-test   # Only runs if tests succeed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simulate Deployment
        run: |
          echo "Deployment successful at $(date)" > deployment.txt

      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: deployment.txt

